apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- prod-register-app-green-deployment.yaml
- prod-green-ing.yaml
- prod-green-service.yaml
namespace: prod
images:
- name: 520707619786.dkr.ecr.us-east-1.amazonaws.com/register-app