apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- dev-register-app-blue-deployment.yaml
- dev-blue-ing.yaml
- dev-blue-service.yaml
namespace: dev
images:
- name: 520707619786.dkr.ecr.us-east-1.amazonaws.com/register-app